[package]
name = "tagged-enum-example"
version = "0.1.0"
authors = ["Dave Rolsky <autarch@urth.org>"]
edition = "2018"

[dependencies]
serde = { version = "~1", features = ["derive"] }
serde_json = "~1"
